{% target '/etc/mcp/nullunit.conf' %}# this file is auto generated by config-curator do not edit by hand
# generated at {{ __timestamp__ }}
# for {{ hostname }}, id: {{ _structure_id }}

[mcp]
host: {{ mcp_host }}
proxy: {{ mcp_proxy }}
job_id: {{ mcp_job_id }}
instance_id: {{ mcp_instance_id }}
instance_cookie: {{ mcp_instance_cookie }}
resource_name: {{ mcp_resource_name }}
resource_index: {{ mcp_resource_index }}

[git]
url: {{ mcp_git_url }}
branch: {{ mcp_git_branch }}

[make]
target: {{ mcp_make_target }}

[packrat]
host: {{ packrat_host }}
proxy: {{ packrat_proxy }}
name: {{ packrat_builder_name }}
psk: {{ packrat_builder_psk }}

[confluence]
host: {{ confluence_host }}
proxy: {{ confluence_proxy }}
username: {{ confluence_username }}
password: {{ confluence_password }}
{% endtarget %}
