{% target '/etc/mcp/nullunit.conf' %}# this file is auto generated by configManager do not edit by hand
# generated at {{ timestamp }}
# for device {{ description }}, id: {{ id }}

[nullunit]
host: {{ mcp_host }}
proxy: {{ mcp_proxy }}
build: {{ mcp_build }}
resource: {{ mcp_resource }}

git_url: {{ mcp_git_url }}
branch: {{ mcp_git_branch }}
target: {{ mcp_target }}

[packrat]
host: {{ packrat_host }}
proxy: {{ packrat_proxy }}
{% endtarget %}
